import CryptoKit
import Foundation

/// The code that opens this build.
///
/// **What this is.** A gate on who joins the private beta. The source is public,
/// so the code itself is not in it — only a salted hash, regenerated by
/// `scripts/set-beta-code.py`.
///
/// **What this is not, and must never be sold as.** Security. Anyone can pull
/// the IPA apart, and the comparison happens on the device, so a determined
/// person gets in. A short code is also brute-forceable in seconds by anyone who
/// bothers.
///
/// That is acceptable *because of what it guards*: entry to a test group. It
/// guards nothing about someone's recordings, which are protected by iOS file
/// encryption and by never leaving the device. If this gate is ever pointed at
/// user data instead, it is the wrong mechanism and should be replaced by a
/// biometric lock — a different feature, with a different promise.
enum BetaAccessCode {

    /// Public by necessity. A salt stops a hash being looked up in a table; it
    /// was never meant to be secret.
    private static let salt = "somna.beta.2026.v1"

    /// SHA-256 of `salt + code`, lowercased hex.
    /// Regenerate with `python scripts/set-beta-code.py <code>`.
    private static let expectedHash =
        "1e1c7df9409380ee013b5732e02118c021a534ba01155044633ad3eff5597918"

    /// Whether `candidate` opens this build.
    ///
    /// Input is trimmed and lowercased before hashing: a code typed on an iPhone
    /// keyboard arrives with an autocapitalised first letter and, often, a
    /// trailing space. Rejecting someone over that would be a support message
    /// for nothing.
    static func matches(_ candidate: String) -> Bool {
        hash(of: normalise(candidate)) == expectedHash
    }

    static func normalise(_ candidate: String) -> String {
        candidate
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
    }

    static func hash(of normalised: String) -> String {
        let digest = SHA256.hash(data: Data((salt + normalised).utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }
}
