import Foundation

extension String {

    /// Localises a key that is only known at runtime.
    ///
    /// `String(localized:defaultValue:)` requires a `StaticString` key so Xcode
    /// can extract it into the String Catalogue at build time. Somna has three
    /// places where the key is computed — event phrasing
    /// (`event.<type>.<confidence>`), calibration advice and the time-of-day
    /// greeting — and those go through `Bundle` instead.
    ///
    /// The trade-off is that extraction cannot see them, so their catalogue
    /// entries are generated by `scripts/generate-strings.py` from the same
    /// source tables. A missing entry degrades to `fallback` rather than showing
    /// a raw key, which is why every call site must pass real English text.
    static func localized(dynamicKey key: String, fallback: String) -> String {
        Bundle.main.localizedString(forKey: key, value: fallback, table: nil)
    }
}
